window.addEventListener("load", function() {
  const H1 = document.createElement('h1');
  H1.append("Webpage Recreation Practice");
  const body = document.querySelector('body');
  body.prepend(H1);
  const p = document.createElement('p');
  p.append('The HTML of this webpage was created with JavaScript.');
  body.append(p);
  const img = document.createElement('img');
  img.src = "https://cdn.download.ams.birds.cornell.edu/api/v1/asset/202984001/900";
  img.alt = "This is an image of a Multicolored Tanager bird from birdsoftheworld.org";
  img.style = "width: 50%";
  body.append(img);
  const H2 = document.createElement('h1');
  H2.append("Facts about the Multicolored Tanager");
  body.append(H2);
  const ul = document.createElement('ul');
  const li1 = document.createElement('li');
  const li2 = document.createElement('li');
  li1.append('It is endemic to the mountains of Colombia.');
  li2.append('It usually searches for insects on the underside of leaves of outer limbs while clinging to leaves with its feet.');
  body.append(ul);
  ul.append(li1);
  ul.append(li2);
  const h3 = document.createElement('h2');
  h3.append('Sources');
  body.append(h3);
  const a = document.createElement('a');
  a.href = "https://en.wikipedia.org/wiki/Multicoloured_tanager";
  a.append('Wikipedia');
  body.append(a);
});